# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170419_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='first_description',
            new_name='main_tags',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='product_name',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='template',
            name='second_description',
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
