# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-03 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20170425_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
