# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170606_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='brand_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='export',
            name='main_tags',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
