# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170607_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.EmailField(max_length=512)),
                ('sales_rank', models.IntegerField()),
                ('monthly_sales_estimate', models.IntegerField()),
                ('asin', models.EmailField(max_length=256)),
                ('small_image_url', models.EmailField(max_length=256)),
                ('reviews', jsonfield.fields.JSONField()),
                ('detail_page_url', models.EmailField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
