# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 17:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170729_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
