# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
